name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build_for_release:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build_for_release
    permissions:
      contents: write
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Create firmware archive
        run: |
          for dir in *Release*/; do
            pushd "${dir}"
            zip -r "../${dir%/}.zip" .
            tar -czf "../${dir%/}.tar.gz" .
            popd
          done

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          files: |
            *.zip
            *.tar.gz
          fail_on_unmatched_files: true
